dist: trusty
sudo: false
language: node_js
node_js:
    - 6.14.0
install:
    - yarn install
    - yarn global add codecov
script:
    - yarn test:ci
cache:
    yarn: true
    directories:
        - node_modules
